package com.ymall.backend.admin.entity;

public enum AdminPermission {
    DASHBOARD_READ,
    MEMBER_READ,
    MEMBER_RESTRICT_LIMITED,
    MEMBER_RESTRICT_ALL,
    SELLER_READ,
    SELLER_APPLICATION_REVIEW,
    SELLER_APPLICATION_DECIDE,
    SUPPORT_REPLY,
    PRODUCT_REVIEW,
    REFUND_STANDARD,
    REFUND_ALL,
    SETTLEMENT_REVIEW,
    SETTLEMENT_APPROVE,
    TASK_SELF,
    TASK_ASSIGN,
    CATEGORY_READ,
    CATEGORY_MANAGE_PARTIAL,
    CATEGORY_MANAGE_ALL,
    ADMIN_MANAGER_MANAGE,
    ADMIN_ALL_MANAGE,
    AUDIT_OWN_READ,
    AUDIT_ALL_READ
}
