-- Generated from the validated YMall PostgreSQL schema after V32.
-- Used only for new environments; existing versioned histories ignore B32.

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    parent_id bigint,
    depth integer DEFAULT 1 NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_addresses (
    id bigint NOT NULL,
    address_name character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    detail_address character varying(255) NOT NULL,
    is_default boolean NOT NULL,
    postal_code character varying(10) NOT NULL,
    recipient_name character varying(50) NOT NULL,
    recipient_phone character varying(20) NOT NULL,
    road_address character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: member_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(100),
    phone character varying(20),
    role character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email_verified_at timestamp without time zone NOT NULL,
    CONSTRAINT members_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_SELLER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(500) NOT NULL,
    read_at timestamp(6) without time zone,
    source_event_id uuid,
    target_url character varying(500),
    title character varying(100) NOT NULL,
    type character varying(30) NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['ORDER_CREATED'::character varying, 'PAYMENT_COMPLETED'::character varying, 'PAYMENT_FAILED'::character varying, 'ORDER_CANCELED'::character varying, 'ORDER_PREPARING'::character varying, 'ORDER_SHIPPED'::character varying, 'ORDER_DELIVERED'::character varying, 'RETURN_REQUESTED'::character varying, 'RETURN_APPROVED'::character varying, 'RETURN_REJECTED'::character varying, 'PRODUCT_QUESTION_CREATED'::character varying, 'PRODUCT_QUESTION_ANSWERED'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_accounts (
    id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT oauth_accounts_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying])::text[])))
);


--
-- Name: oauth_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.oauth_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    fulfillment_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    line_total numeric(22,2) NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    refunded_quantity integer DEFAULT 0 NOT NULL,
    shipping_carrier character varying(30),
    tracking_number character varying(100),
    shipping_fee numeric(12,2) DEFAULT 0 NOT NULL,
    delivered_at timestamp without time zone,
    carrier character varying(50),
    shipped_at timestamp without time zone,
    CONSTRAINT order_items_fulfillment_status_check CHECK (((fulfillment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PREPARING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_outbox_events (
    event_id uuid NOT NULL,
    attempt_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    event_type character varying(50) NOT NULL,
    last_error character varying(1000),
    member_id bigint NOT NULL,
    next_attempt_at timestamp(6) with time zone NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    order_id bigint NOT NULL,
    payload text NOT NULL,
    published_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    version integer NOT NULL,
    CONSTRAINT order_outbox_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['ORDER_CREATED'::character varying, 'PAYMENT_COMPLETED'::character varying, 'PAYMENT_FAILED'::character varying, 'ORDER_CANCELED'::character varying, 'ORDER_PREPARING'::character varying, 'ORDER_SHIPPED'::character varying, 'ORDER_DELIVERED'::character varying, 'REFUND_COMPLETED'::character varying])::text[]))),
    CONSTRAINT order_outbox_events_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    detail_address character varying(255),
    postal_code character varying(10),
    recipient_name character varying(50),
    recipient_phone character varying(20),
    road_address character varying(255),
    idempotency_key character varying(100) NOT NULL,
    status character varying(30) NOT NULL,
    total_amount numeric(38,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    inventory_reserved boolean NOT NULL,
    payment_order_id character varying(64) NOT NULL,
    delivery_request character varying(100),
    delivered_at timestamp without time zone,
    shipping_amount numeric(38,2) DEFAULT 0 NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PAYMENT_FAILED'::character varying, 'CANCELED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'REFUNDED'::character varying, 'PREPARING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_refund_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_refund_items (
    id bigint NOT NULL,
    refund_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    quantity integer NOT NULL,
    amount numeric(38,2) NOT NULL,
    CONSTRAINT payment_refund_items_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT payment_refund_items_quantity_check CHECK ((quantity > 0))
);


--
-- Name: payment_refund_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.payment_refund_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: payment_refund_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.payment_refund_items_id_seq OWNED BY public.payment_refund_items.id;


--
-- Name: payment_refunds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_refunds (
    id bigint NOT NULL,
    payment_id bigint NOT NULL,
    order_id bigint NOT NULL,
    idempotency_key character varying(100) NOT NULL,
    type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    amount numeric(38,2) NOT NULL,
    reason character varying(200) NOT NULL,
    requested_by_member_id bigint NOT NULL,
    requested_by_role character varying(30) NOT NULL,
    provider_status character varying(30),
    provider_balance_amount numeric(38,2),
    failure_code character varying(100),
    failure_message character varying(500),
    created_at timestamp without time zone NOT NULL,
    processed_at timestamp without time zone
);


--
-- Name: payment_refunds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.payment_refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: payment_refunds_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.payment_refunds_id_seq OWNED BY public.payment_refunds.id;


--
-- Name: payment_webhook_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_webhook_events (
    id bigint NOT NULL,
    transmission_id character varying(200) NOT NULL,
    event_type character varying(50) NOT NULL,
    payment_key character varying(200) NOT NULL,
    payment_order_id character varying(64) NOT NULL,
    requested_status character varying(30) NOT NULL,
    verified_status character varying(30) NOT NULL,
    result character varying(30) NOT NULL,
    event_created_at timestamp without time zone NOT NULL,
    processed_at timestamp without time zone NOT NULL
);


--
-- Name: payment_webhook_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.payment_webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: payment_webhook_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.payment_webhook_events_id_seq OWNED BY public.payment_webhook_events.id;


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    failure_message character varying(255),
    idempotency_key character varying(100) NOT NULL,
    order_status character varying(30) NOT NULL,
    processed_at timestamp(6) without time zone NOT NULL,
    result character varying(20) NOT NULL,
    order_id bigint NOT NULL,
    approved_amount numeric(38,2),
    approved_at timestamp(6) with time zone,
    failure_code character varying(100),
    method character varying(50),
    payment_key character varying(200),
    payment_order_id character varying(64),
    requested_amount numeric(38,2),
    provider_status character varying(30),
    CONSTRAINT payments_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PAYMENT_FAILED'::character varying, 'CANCELED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'REFUNDED'::character varying, 'PREPARING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[]))),
    CONSTRAINT payments_result_check CHECK (((result)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILURE'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processed_order_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_order_events (
    id bigint NOT NULL,
    event_id uuid NOT NULL,
    event_type character varying(30) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    order_id bigint NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL,
    result character varying(20) NOT NULL,
    CONSTRAINT processed_order_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['ORDER_CREATED'::character varying, 'PAYMENT_COMPLETED'::character varying, 'PAYMENT_FAILED'::character varying, 'ORDER_CANCELED'::character varying, 'ORDER_PREPARING'::character varying, 'ORDER_SHIPPED'::character varying, 'ORDER_DELIVERED'::character varying])::text[]))),
    CONSTRAINT processed_order_events_result_check CHECK (((result)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: processed_order_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.processed_order_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processed_order_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_detail_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_detail_images (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    original_url text,
    image_url text NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_product_detail_images_sort_order CHECK ((sort_order >= 0))
);


--
-- Name: product_detail_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_detail_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_detail_images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_detail_images_id_seq OWNED BY public.product_detail_images.id;


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    image_url text NOT NULL,
    original_url text,
    sort_order integer NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_question_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_question_answers (
    answer_id bigint NOT NULL,
    question_id bigint NOT NULL,
    seller_profile_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: product_question_answers_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_question_answers_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_question_answers_answer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_question_answers_answer_id_seq OWNED BY public.product_question_answers.answer_id;


--
-- Name: product_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_questions (
    question_id bigint NOT NULL,
    product_id bigint NOT NULL,
    member_id bigint NOT NULL,
    title character varying(100) NOT NULL,
    content text NOT NULL,
    is_private boolean DEFAULT false NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT ck_product_questions_status CHECK (((status)::text = ANY ((ARRAY['WAITING'::character varying, 'ANSWERED'::character varying])::text[])))
);


--
-- Name: product_questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_questions_question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_questions_question_id_seq OWNED BY public.product_questions.question_id;


--
-- Name: product_return_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_return_requests (
    return_request_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    member_id bigint NOT NULL,
    quantity integer NOT NULL,
    reason character varying(500) NOT NULL,
    status character varying(20) NOT NULL,
    seller_response character varying(500),
    payment_refund_id bigint,
    requested_at timestamp without time zone NOT NULL,
    processed_at timestamp without time zone,
    CONSTRAINT ck_return_request_quantity CHECK ((quantity > 0)),
    CONSTRAINT ck_return_request_status CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: product_return_requests_return_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_return_requests_return_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_return_requests_return_request_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_return_requests_return_request_id_seq OWNED BY public.product_return_requests.return_request_id;


--
-- Name: product_revision_detail_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_revision_detail_images (
    product_revision_detail_image_id bigint NOT NULL,
    product_revision_id bigint NOT NULL,
    original_url text,
    image_url text NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: product_revision_detail_image_product_revision_detail_image_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_revision_detail_image_product_revision_detail_image_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_revision_detail_image_product_revision_detail_image_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_revision_detail_image_product_revision_detail_image_seq OWNED BY public.product_revision_detail_images.product_revision_detail_image_id;


--
-- Name: product_revision_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_revision_images (
    product_revision_image_id bigint NOT NULL,
    product_revision_id bigint NOT NULL,
    original_url text,
    image_url text NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: product_revision_images_product_revision_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_revision_images_product_revision_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_revision_images_product_revision_image_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_revision_images_product_revision_image_id_seq OWNED BY public.product_revision_images.product_revision_image_id;


--
-- Name: product_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_revisions (
    product_revision_id bigint NOT NULL,
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    brand character varying(100),
    thumbnail_url text,
    status character varying(30) NOT NULL,
    rejection_reason character varying(500),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    reviewed_at timestamp without time zone
);


--
-- Name: product_revisions_product_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_revisions_product_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_revisions_product_revision_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_revisions_product_revision_id_seq OWNED BY public.product_revisions.product_revision_id;


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    brand character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    discount_percentage numeric(5,2),
    name character varying(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    rating numeric(3,2),
    status character varying(30) NOT NULL,
    stock integer NOT NULL,
    thumbnail_url text,
    updated_at timestamp(6) without time zone NOT NULL,
    category_id bigint NOT NULL,
    seller_profile_id bigint,
    rejection_reason character varying(500),
    discount_end_date date,
    discount_start_date date,
    free_shipping boolean DEFAULT true NOT NULL,
    shipping_fee numeric(12,2) DEFAULT 0 NOT NULL,
    estimated_delivery_days integer DEFAULT 3 NOT NULL,
    CONSTRAINT chk_products_discount_period CHECK ((((discount_percentage = (0)::numeric) AND (discount_start_date IS NULL) AND (discount_end_date IS NULL)) OR ((discount_percentage > (0)::numeric) AND (discount_start_date IS NOT NULL) AND (discount_end_date IS NOT NULL) AND (discount_start_date <= discount_end_date)))),
    CONSTRAINT chk_products_estimated_delivery_days CHECK (((estimated_delivery_days >= 1) AND (estimated_delivery_days <= 30))),
    CONSTRAINT chk_products_shipping_fee CHECK ((((free_shipping = true) AND (shipping_fee = (0)::numeric)) OR ((free_shipping = false) AND (shipping_fee > (0)::numeric)))),
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'SOLD_OUT'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_summaries (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    summary_json text NOT NULL,
    source_review_count bigint NOT NULL,
    source_updated_at timestamp without time zone,
    model_version character varying(200) NOT NULL,
    generated_at timestamp without time zone NOT NULL
);


--
-- Name: review_summaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.review_summaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: review_summaries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.review_summaries_id_seq OWNED BY public.review_summaries.id;


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    rating integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_applications (
    id bigint NOT NULL,
    business_number character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    rejection_reason character varying(500),
    reviewed_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    store_name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    reviewed_by bigint,
    CONSTRAINT seller_applications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: seller_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_profiles (
    id bigint NOT NULL,
    business_number character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    store_name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: seller_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_settlement_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_settlement_accounts (
    id bigint NOT NULL,
    seller_profile_id bigint NOT NULL,
    bank_code character varying(3) NOT NULL,
    account_holder_ciphertext text NOT NULL,
    account_number_ciphertext text NOT NULL,
    account_number_last4 character varying(4) NOT NULL,
    verification_status character varying(20) NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: seller_settlement_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seller_settlement_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seller_settlement_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.seller_settlement_accounts_id_seq OWNED BY public.seller_settlement_accounts.id;


--
-- Name: settlement_ledger_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_ledger_entries (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    entry_type character varying(20) NOT NULL,
    fee_amount numeric(38,2) NOT NULL,
    gross_amount numeric(38,2) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    settlement_amount numeric(38,2) NOT NULL,
    source_event_id uuid NOT NULL,
    source_key character varying(120) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    order_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    payment_refund_id bigint,
    seller_profile_id bigint NOT NULL,
    settlement_request_id bigint,
    CONSTRAINT settlement_ledger_entries_entry_type_check CHECK (((entry_type)::text = ANY ((ARRAY['SALE'::character varying, 'REFUND'::character varying])::text[]))),
    CONSTRAINT settlement_ledger_entries_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'AVAILABLE'::character varying, 'REQUESTED'::character varying, 'PAID'::character varying])::text[])))
);


--
-- Name: settlement_ledger_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement_ledger_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_ledger_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_request_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_request_histories (
    id bigint NOT NULL,
    settlement_request_id bigint NOT NULL,
    from_status character varying(20),
    to_status character varying(20) NOT NULL,
    actor_member_id bigint NOT NULL,
    reason character varying(500),
    created_at timestamp with time zone NOT NULL
);


--
-- Name: settlement_request_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.settlement_request_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: settlement_request_histories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.settlement_request_histories_id_seq OWNED BY public.settlement_request_histories.id;


--
-- Name: settlement_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_requests (
    id bigint NOT NULL,
    seller_profile_id bigint NOT NULL,
    period_start date,
    period_end date,
    status character varying(20) NOT NULL,
    gross_amount numeric(38,2) NOT NULL,
    fee_amount numeric(38,2) NOT NULL,
    settlement_amount numeric(38,2) NOT NULL,
    rejection_reason character varying(500),
    reviewed_by_member_id bigint,
    reviewed_at timestamp with time zone,
    paid_at timestamp with time zone,
    mock_payment_reference character varying(80),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: settlement_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.settlement_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: settlement_requests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.settlement_requests_id_seq OWNED BY public.settlement_requests.id;


--
-- Name: wishlist_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wishlist_items (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    product_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: wishlist_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.wishlist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: wishlist_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.wishlist_items_id_seq OWNED BY public.wishlist_items.id;


--
-- Name: payment_refund_items id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refund_items ALTER COLUMN id SET DEFAULT nextval('public.payment_refund_items_id_seq'::regclass);


--
-- Name: payment_refunds id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refunds ALTER COLUMN id SET DEFAULT nextval('public.payment_refunds_id_seq'::regclass);


--
-- Name: payment_webhook_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_webhook_events ALTER COLUMN id SET DEFAULT nextval('public.payment_webhook_events_id_seq'::regclass);


--
-- Name: product_detail_images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail_images ALTER COLUMN id SET DEFAULT nextval('public.product_detail_images_id_seq'::regclass);


--
-- Name: product_question_answers answer_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_question_answers ALTER COLUMN answer_id SET DEFAULT nextval('public.product_question_answers_answer_id_seq'::regclass);


--
-- Name: product_questions question_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions ALTER COLUMN question_id SET DEFAULT nextval('public.product_questions_question_id_seq'::regclass);


--
-- Name: product_return_requests return_request_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_return_requests ALTER COLUMN return_request_id SET DEFAULT nextval('public.product_return_requests_return_request_id_seq'::regclass);


--
-- Name: product_revision_detail_images product_revision_detail_image_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revision_detail_images ALTER COLUMN product_revision_detail_image_id SET DEFAULT nextval('public.product_revision_detail_image_product_revision_detail_image_seq'::regclass);


--
-- Name: product_revision_images product_revision_image_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revision_images ALTER COLUMN product_revision_image_id SET DEFAULT nextval('public.product_revision_images_product_revision_image_id_seq'::regclass);


--
-- Name: product_revisions product_revision_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revisions ALTER COLUMN product_revision_id SET DEFAULT nextval('public.product_revisions_product_revision_id_seq'::regclass);


--
-- Name: review_summaries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_summaries ALTER COLUMN id SET DEFAULT nextval('public.review_summaries_id_seq'::regclass);


--
-- Name: seller_settlement_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlement_accounts ALTER COLUMN id SET DEFAULT nextval('public.seller_settlement_accounts_id_seq'::regclass);


--
-- Name: settlement_request_histories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_request_histories ALTER COLUMN id SET DEFAULT nextval('public.settlement_request_histories_id_seq'::regclass);


--
-- Name: settlement_requests id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_requests ALTER COLUMN id SET DEFAULT nextval('public.settlement_requests_id_seq'::regclass);


--
-- Name: wishlist_items id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items ALTER COLUMN id SET DEFAULT nextval('public.wishlist_items_id_seq'::regclass);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: member_addresses member_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_addresses
    ADD CONSTRAINT member_addresses_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: oauth_accounts oauth_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: order_outbox_events order_outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_outbox_events
    ADD CONSTRAINT order_outbox_events_pkey PRIMARY KEY (event_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payment_refund_items payment_refund_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refund_items
    ADD CONSTRAINT payment_refund_items_pkey PRIMARY KEY (id);


--
-- Name: payment_refunds payment_refunds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refunds
    ADD CONSTRAINT payment_refunds_pkey PRIMARY KEY (id);


--
-- Name: payment_webhook_events payment_webhook_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_webhook_events
    ADD CONSTRAINT payment_webhook_events_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: processed_order_events processed_order_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_order_events
    ADD CONSTRAINT processed_order_events_pkey PRIMARY KEY (id);


--
-- Name: product_detail_images product_detail_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail_images
    ADD CONSTRAINT product_detail_images_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: product_question_answers product_question_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_question_answers
    ADD CONSTRAINT product_question_answers_pkey PRIMARY KEY (answer_id);


--
-- Name: product_question_answers product_question_answers_question_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_question_answers
    ADD CONSTRAINT product_question_answers_question_id_key UNIQUE (question_id);


--
-- Name: product_questions product_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT product_questions_pkey PRIMARY KEY (question_id);


--
-- Name: product_return_requests product_return_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_return_requests
    ADD CONSTRAINT product_return_requests_pkey PRIMARY KEY (return_request_id);


--
-- Name: product_revision_detail_images product_revision_detail_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revision_detail_images
    ADD CONSTRAINT product_revision_detail_images_pkey PRIMARY KEY (product_revision_detail_image_id);


--
-- Name: product_revision_images product_revision_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revision_images
    ADD CONSTRAINT product_revision_images_pkey PRIMARY KEY (product_revision_image_id);


--
-- Name: product_revisions product_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revisions
    ADD CONSTRAINT product_revisions_pkey PRIMARY KEY (product_revision_id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: review_summaries review_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_summaries
    ADD CONSTRAINT review_summaries_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: seller_applications seller_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_applications
    ADD CONSTRAINT seller_applications_pkey PRIMARY KEY (id);


--
-- Name: seller_profiles seller_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_profiles
    ADD CONSTRAINT seller_profiles_pkey PRIMARY KEY (id);


--
-- Name: seller_settlement_accounts seller_settlement_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlement_accounts
    ADD CONSTRAINT seller_settlement_accounts_pkey PRIMARY KEY (id);


--
-- Name: seller_settlement_accounts seller_settlement_accounts_seller_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlement_accounts
    ADD CONSTRAINT seller_settlement_accounts_seller_profile_id_key UNIQUE (seller_profile_id);


--
-- Name: settlement_ledger_entries settlement_ledger_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT settlement_ledger_entries_pkey PRIMARY KEY (id);


--
-- Name: settlement_request_histories settlement_request_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_request_histories
    ADD CONSTRAINT settlement_request_histories_pkey PRIMARY KEY (id);


--
-- Name: settlement_requests settlement_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_requests
    ADD CONSTRAINT settlement_requests_pkey PRIMARY KEY (id);


--
-- Name: seller_applications uk2s0nwfcleo89c6i6bmi3klfa6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_applications
    ADD CONSTRAINT uk2s0nwfcleo89c6i6bmi3klfa6 UNIQUE (member_id);


--
-- Name: payments uk35yqdahtiysne6iij9ske72bj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk35yqdahtiysne6iij9ske72bj UNIQUE (payment_key);


--
-- Name: seller_profiles uk98icw4xfidptbiac3x4avyqrb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_profiles
    ADD CONSTRAINT uk98icw4xfidptbiac3x4avyqrb UNIQUE (business_number);


--
-- Name: members uk9d30a9u1qpg8eou0otgkwrp5d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT uk9d30a9u1qpg8eou0otgkwrp5d UNIQUE (email);


--
-- Name: notifications uk9grtlg60yfd75v896x8v16lwp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT uk9grtlg60yfd75v896x8v16lwp UNIQUE (source_event_id);


--
-- Name: cart_items uk_cart_items_member_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT uk_cart_items_member_product UNIQUE (member_id, product_id);


--
-- Name: oauth_accounts uk_oauth_accounts_member_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT uk_oauth_accounts_member_provider UNIQUE (member_id, provider);


--
-- Name: oauth_accounts uk_oauth_accounts_provider_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT uk_oauth_accounts_provider_user UNIQUE (provider, provider_user_id);


--
-- Name: orders uk_orders_member_idempotency_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_member_idempotency_key UNIQUE (member_id, idempotency_key);


--
-- Name: payment_refunds uk_payment_refunds_order_idempotency_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refunds
    ADD CONSTRAINT uk_payment_refunds_order_idempotency_key UNIQUE (order_id, idempotency_key);


--
-- Name: payment_webhook_events uk_payment_webhook_events_transmission_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_webhook_events
    ADD CONSTRAINT uk_payment_webhook_events_transmission_id UNIQUE (transmission_id);


--
-- Name: payments uk_payments_order_idempotency_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk_payments_order_idempotency_key UNIQUE (order_id, idempotency_key);


--
-- Name: review_summaries uk_review_summaries_product_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_summaries
    ADD CONSTRAINT uk_review_summaries_product_id UNIQUE (product_id);


--
-- Name: reviews uk_reviews_order_item_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT uk_reviews_order_item_id UNIQUE (order_item_id);


--
-- Name: wishlist_items uk_wishlist_items_member_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT uk_wishlist_items_member_product UNIQUE (member_id, product_id);


--
-- Name: seller_profiles ukby7wfecgoaqeno84who215vtf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_profiles
    ADD CONSTRAINT ukby7wfecgoaqeno84who215vtf UNIQUE (member_id);


--
-- Name: processed_order_events ukgwrwxda1cq54o59kic50eaobg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_order_events
    ADD CONSTRAINT ukgwrwxda1cq54o59kic50eaobg UNIQUE (event_id);


--
-- Name: categories ukoul14ho7bctbefv8jywp5v3i2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug);


--
-- Name: settlement_ledger_entries ukr8ax40phlfeyq19wlgsa0koxf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT ukr8ax40phlfeyq19wlgsa0koxf UNIQUE (source_key);


--
-- Name: wishlist_items wishlist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_pkey PRIMARY KEY (id);


--
-- Name: idx_categories_active_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_active_order ON public.categories USING btree (active, depth, display_order);


--
-- Name: idx_categories_parent_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_parent_order ON public.categories USING btree (parent_id, display_order);


--
-- Name: idx_order_items_fulfillment_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_items_fulfillment_status ON public.order_items USING btree (fulfillment_status);


--
-- Name: idx_order_outbox_publishable; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_outbox_publishable ON public.order_outbox_events USING btree (status, next_attempt_at, created_at);


--
-- Name: idx_order_outbox_published_cleanup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_outbox_published_cleanup ON public.order_outbox_events USING btree (status, published_at);


--
-- Name: idx_orders_pending_expiration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_pending_expiration ON public.orders USING btree (created_at, id) WHERE (((status)::text = 'PENDING_PAYMENT'::text) AND (inventory_reserved = true));


--
-- Name: idx_payment_refund_items_order_item_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_refund_items_order_item_id ON public.payment_refund_items USING btree (order_item_id);


--
-- Name: idx_payment_refunds_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_refunds_order_id ON public.payment_refunds USING btree (order_id, created_at DESC);


--
-- Name: idx_payment_webhook_events_payment_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_webhook_events_payment_key ON public.payment_webhook_events USING btree (payment_key);


--
-- Name: idx_processed_order_events_order_result_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_processed_order_events_order_result_id ON public.processed_order_events USING btree (order_id, result, id DESC);


--
-- Name: idx_product_detail_images_product_sort_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_detail_images_product_sort_order ON public.product_detail_images USING btree (product_id, sort_order, id);


--
-- Name: idx_product_questions_product_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_questions_product_created ON public.product_questions USING btree (product_id, created_at DESC);


--
-- Name: idx_product_questions_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_questions_status_created ON public.product_questions USING btree (status, created_at DESC);


--
-- Name: idx_product_revisions_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_revisions_status_created ON public.product_revisions USING btree (status, created_at DESC);


--
-- Name: idx_return_request_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_return_request_member ON public.product_return_requests USING btree (member_id, requested_at DESC);


--
-- Name: idx_return_request_order_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_return_request_order_item ON public.product_return_requests USING btree (order_item_id);


--
-- Name: idx_return_request_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_return_request_status ON public.product_return_requests USING btree (status, requested_at);


--
-- Name: idx_seller_applications_business_number; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_seller_applications_business_number ON public.seller_applications USING btree (business_number);


--
-- Name: idx_seller_applications_status_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_seller_applications_status_created_at ON public.seller_applications USING btree (status, created_at);


--
-- Name: idx_settlement_history_request_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_history_request_created ON public.settlement_request_histories USING btree (settlement_request_id, created_at);


--
-- Name: idx_settlement_ledger_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_ledger_order ON public.settlement_ledger_entries USING btree (order_id);


--
-- Name: idx_settlement_ledger_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_ledger_request ON public.settlement_ledger_entries USING btree (settlement_request_id);


--
-- Name: idx_settlement_ledger_seller_status_occurred; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_ledger_seller_status_occurred ON public.settlement_ledger_entries USING btree (seller_profile_id, status, occurred_at DESC);


--
-- Name: idx_settlement_request_seller_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_request_seller_created ON public.settlement_requests USING btree (seller_profile_id, created_at DESC);


--
-- Name: idx_settlement_request_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_request_status_created ON public.settlement_requests USING btree (status, created_at DESC);


--
-- Name: idx_wishlist_items_member_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wishlist_items_member_created_at ON public.wishlist_items USING btree (member_id, created_at DESC);


--
-- Name: uk_notifications_source_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_notifications_source_event_id ON public.notifications USING btree (source_event_id);


--
-- Name: uk_orders_payment_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_orders_payment_order_id ON public.orders USING btree (payment_order_id);


--
-- Name: uk_payments_payment_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_payments_payment_key ON public.payments USING btree (payment_key) WHERE (payment_key IS NOT NULL);


--
-- Name: uq_product_revisions_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_product_revisions_pending ON public.product_revisions USING btree (product_id) WHERE ((status)::text = 'PENDING'::text);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: orders fk2vq7lo4gkknrmghj3rqpqqg6s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk2vq7lo4gkknrmghj3rqpqqg6s FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: reviews fk2x2x74lnliqmt91bc1w95ll8n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk2x2x74lnliqmt91bc1w95ll8n FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: settlement_ledger_entries fk3vo27x3w96iv7o3xukxfl6x6p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT fk3vo27x3w96iv7o3xukxfl6x6p FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: settlement_ledger_entries fk4wfb8plda916tkpm65br1bbvy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT fk4wfb8plda916tkpm65br1bbvy FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: reviews fk6wsc8rr8tb1fc782foh3mjc8q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk6wsc8rr8tb1fc782foh3mjc8q FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: settlement_ledger_entries fk8e339n3cdf5mdp1lp7f9pslr9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT fk8e339n3cdf5mdp1lp7f9pslr9 FOREIGN KEY (seller_profile_id) REFERENCES public.seller_profiles(id);


--
-- Name: categories fk_categories_parent; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES public.categories(id);


--
-- Name: product_detail_images fk_product_detail_images_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail_images
    ADD CONSTRAINT fk_product_detail_images_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: product_question_answers fk_product_question_answers_question; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_question_answers
    ADD CONSTRAINT fk_product_question_answers_question FOREIGN KEY (question_id) REFERENCES public.product_questions(question_id) ON DELETE CASCADE;


--
-- Name: product_question_answers fk_product_question_answers_seller; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_question_answers
    ADD CONSTRAINT fk_product_question_answers_seller FOREIGN KEY (seller_profile_id) REFERENCES public.seller_profiles(id);


--
-- Name: product_questions fk_product_questions_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT fk_product_questions_member FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: product_questions fk_product_questions_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT fk_product_questions_product FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: product_return_requests fk_return_request_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_return_requests
    ADD CONSTRAINT fk_return_request_member FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: product_return_requests fk_return_request_order_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_return_requests
    ADD CONSTRAINT fk_return_request_order_item FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: product_return_requests fk_return_request_payment_refund; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_return_requests
    ADD CONSTRAINT fk_return_request_payment_refund FOREIGN KEY (payment_refund_id) REFERENCES public.payment_refunds(id);


--
-- Name: seller_settlement_accounts fk_seller_settlement_account_profile; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlement_accounts
    ADD CONSTRAINT fk_seller_settlement_account_profile FOREIGN KEY (seller_profile_id) REFERENCES public.seller_profiles(id);


--
-- Name: settlement_request_histories fk_settlement_history_actor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_request_histories
    ADD CONSTRAINT fk_settlement_history_actor FOREIGN KEY (actor_member_id) REFERENCES public.members(id);


--
-- Name: settlement_request_histories fk_settlement_history_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_request_histories
    ADD CONSTRAINT fk_settlement_history_request FOREIGN KEY (settlement_request_id) REFERENCES public.settlement_requests(id);


--
-- Name: settlement_ledger_entries fk_settlement_ledger_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT fk_settlement_ledger_request FOREIGN KEY (settlement_request_id) REFERENCES public.settlement_requests(id);


--
-- Name: settlement_requests fk_settlement_request_reviewer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_requests
    ADD CONSTRAINT fk_settlement_request_reviewer FOREIGN KEY (reviewed_by_member_id) REFERENCES public.members(id);


--
-- Name: settlement_requests fk_settlement_request_seller_profile; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_requests
    ADD CONSTRAINT fk_settlement_request_seller_profile FOREIGN KEY (seller_profile_id) REFERENCES public.seller_profiles(id);


--
-- Name: wishlist_items fk_wishlist_items_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT fk_wishlist_items_member FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


--
-- Name: wishlist_items fk_wishlist_items_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT fk_wishlist_items_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: seller_profiles fke0cg66jcjwh5st92l7wju0p0g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_profiles
    ADD CONSTRAINT fke0cg66jcjwh5st92l7wju0p0g FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: oauth_accounts fkfg5jcva0fk0koeoepk3fjp48c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT fkfg5jcva0fk0koeoepk3fjp48c FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: seller_applications fkglyo9bh6q3c94r6rfovdjsdxs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_applications
    ADD CONSTRAINT fkglyo9bh6q3c94r6rfovdjsdxs FOREIGN KEY (reviewed_by) REFERENCES public.members(id);


--
-- Name: member_addresses fkijf5s4glfq6hc5n42fr4tx3x4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_addresses
    ADD CONSTRAINT fkijf5s4glfq6hc5n42fr4tx3x4 FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: products fkkysx1vsiuq47yg7rdic09t4ic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkkysx1vsiuq47yg7rdic09t4ic FOREIGN KEY (seller_profile_id) REFERENCES public.seller_profiles(id);


--
-- Name: cart_items fkmyrsw3rg5yxntcqv45s8q6msh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkmyrsw3rg5yxntcqv45s8q6msh FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: notifications fkojs7hmp2vm78xakpqgr1hgsbk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkojs7hmp2vm78xakpqgr1hgsbk FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: reviews fkpl51cejpw4gy5swfar8br9ngi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: settlement_ledger_entries fkqd3d4aby1g45ular6ve0k1pbd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_ledger_entries
    ADD CONSTRAINT fkqd3d4aby1g45ular6ve0k1pbd FOREIGN KEY (payment_refund_id) REFERENCES public.payment_refunds(id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: categories fksaok720gsu4u2wrgbk10b5n8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);


--
-- Name: seller_applications fktdd6onaeqlbo9jhx24i0ofm8f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_applications
    ADD CONSTRAINT fktdd6onaeqlbo9jhx24i0ofm8f FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: payment_refund_items payment_refund_items_order_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refund_items
    ADD CONSTRAINT payment_refund_items_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: payment_refund_items payment_refund_items_refund_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refund_items
    ADD CONSTRAINT payment_refund_items_refund_id_fkey FOREIGN KEY (refund_id) REFERENCES public.payment_refunds(id) ON DELETE CASCADE;


--
-- Name: payment_refunds payment_refunds_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refunds
    ADD CONSTRAINT payment_refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: payment_refunds payment_refunds_payment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_refunds
    ADD CONSTRAINT payment_refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id);


--
-- Name: product_revision_detail_images product_revision_detail_images_product_revision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revision_detail_images
    ADD CONSTRAINT product_revision_detail_images_product_revision_id_fkey FOREIGN KEY (product_revision_id) REFERENCES public.product_revisions(product_revision_id) ON DELETE CASCADE;


--
-- Name: product_revision_images product_revision_images_product_revision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revision_images
    ADD CONSTRAINT product_revision_images_product_revision_id_fkey FOREIGN KEY (product_revision_id) REFERENCES public.product_revisions(product_revision_id) ON DELETE CASCADE;


--
-- Name: product_revisions product_revisions_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revisions
    ADD CONSTRAINT product_revisions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: product_revisions product_revisions_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_revisions
    ADD CONSTRAINT product_revisions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: review_summaries review_summaries_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_summaries
    ADD CONSTRAINT review_summaries_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
