CREATE TABLE support_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members (id),
    requester_type VARCHAR(20) NOT NULL,
    category VARCHAR(30) NOT NULL,
    title VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL,
    assigned_admin_id BIGINT REFERENCES members (id),
    related_order_id BIGINT,
    related_product_id BIGINT,
    related_settlement_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    CONSTRAINT support_inquiries_requester_type_check
        CHECK (requester_type IN ('CUSTOMER', 'SELLER')),
    CONSTRAINT support_inquiries_status_check
        CHECK (status IN (
            'WAITING', 'IN_PROGRESS', 'ANSWERED', 'LIVE_REQUESTED',
            'LIVE_OFFERED', 'LIVE_ACTIVE', 'CLOSED'
        ))
);

CREATE TABLE support_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT NOT NULL REFERENCES support_inquiries (id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES members (id),
    author_role VARCHAR(20) NOT NULL,
    type VARCHAR(20) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    client_message_id UUID,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT support_messages_author_role_check
        CHECK (author_role IN ('ROLE_USER', 'ROLE_SELLER', 'ROLE_ADMIN')),
    CONSTRAINT support_messages_type_check
        CHECK (type IN ('INQUIRY', 'REPLY', 'LIVE_CHAT', 'SYSTEM', 'RESOLUTION')),
    CONSTRAINT uk_support_message_client_id UNIQUE (inquiry_id, client_message_id)
);

CREATE TABLE support_chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT NOT NULL UNIQUE REFERENCES support_inquiries (id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES members (id),
    initiated_by VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP,
    offered_at TIMESTAMP,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT support_chat_sessions_initiated_by_check
        CHECK (initiated_by IN ('USER_REQUEST', 'ADMIN_OFFER')),
    CONSTRAINT support_chat_sessions_status_check
        CHECK (status IN ('WAITING', 'ACTIVE', 'ENDED', 'EXPIRED', 'REJECTED'))
);

CREATE INDEX idx_support_inquiries_member_created
    ON support_inquiries (member_id, created_at DESC, id DESC);
CREATE INDEX idx_support_inquiries_admin_queue
    ON support_inquiries (status, created_at, id);
CREATE INDEX idx_support_messages_inquiry_created
    ON support_messages (inquiry_id, created_at, id);

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (
    type IN (
        'ORDER_CREATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'ORDER_CANCELED',
        'ORDER_PREPARING', 'ORDER_SHIPPED', 'ORDER_DELIVERED', 'RETURN_REQUESTED',
        'RETURN_APPROVED', 'RETURN_REJECTED', 'PRODUCT_QUESTION_CREATED',
        'PRODUCT_QUESTION_ANSWERED', 'SUPPORT_INQUIRY_CREATED', 'SUPPORT_REPLY',
        'SUPPORT_LIVE_REQUESTED', 'SUPPORT_LIVE_OFFERED', 'SUPPORT_LIVE_STATUS',
        'SUPPORT_CLOSED'
    )
);
