CREATE TABLE support_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES support_messages (id) ON DELETE CASCADE,
    original_file_name VARCHAR(255) NOT NULL,
    stored_path VARCHAR(500) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_support_attachments_message
    ON support_attachments (message_id, id);
