ALTER TABLE members
    ADD COLUMN admin_grade VARCHAR(20),
    ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0;

UPDATE members
SET admin_grade = 'SUPER_ADMIN'
WHERE role = 'ROLE_ADMIN';

ALTER TABLE members
    ADD CONSTRAINT members_admin_grade_check CHECK (
        (role = 'ROLE_ADMIN' AND admin_grade IN ('MANAGER', 'SUPERVISOR', 'SUPER_ADMIN'))
        OR (role <> 'ROLE_ADMIN' AND admin_grade IS NULL)
    );

CREATE TABLE admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_member_id BIGINT NOT NULL REFERENCES members (id),
    actor_grade VARCHAR(20) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    before_value VARCHAR(1000),
    after_value VARCHAR(1000),
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT admin_audit_logs_actor_grade_check
        CHECK (actor_grade IN ('MANAGER', 'SUPERVISOR', 'SUPER_ADMIN')),
    CONSTRAINT admin_audit_logs_target_type_check
        CHECK (target_type IN (
            'MEMBER', 'SELLER_APPLICATION', 'PRODUCT', 'ORDER', 'SETTLEMENT', 'CATEGORY'
        )),
    CONSTRAINT admin_audit_logs_action_check
        CHECK (action IN (
            'ADMIN_ROLE_CHANGED', 'MEMBER_RESTRICTION_CHANGED',
            'SELLER_APPLICATION_REVIEWED', 'PRODUCT_REVIEWED', 'REFUND_PROCESSED',
            'SETTLEMENT_APPROVED', 'CATEGORY_POLICY_CHANGED'
        ))
);

CREATE INDEX idx_admin_audit_logs_actor_created
    ON admin_audit_logs (actor_member_id, created_at DESC, id DESC);
CREATE INDEX idx_admin_audit_logs_target_created
    ON admin_audit_logs (target_type, target_id, created_at DESC, id DESC);
CREATE INDEX idx_admin_audit_logs_action_created
    ON admin_audit_logs (action, created_at DESC, id DESC);
