server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ymall
    username: ymall_user
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

ymall:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 30m
