server:
  port: 8080

spring:
  profiles:
    default: local

  application:
    name: backend

  jpa:
    properties:
      hibernate:
        format_sql: true

ymall:
  file:
    upload-dir: ./uploads
    image-url-prefix: /images
    thumbnail-width: 300
    thumbnail-height: 300
