package com.ymall.backend.notification.entity;

public enum NotificationType {
    ORDER_CREATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    ORDER_CANCELED,
    ORDER_PREPARING,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    PRODUCT_QUESTION_CREATED,
    PRODUCT_QUESTION_ANSWERED
}
